### ISSUE TITLE
publish on npm?

### ISSUE THREAD

**Issue by seiyria** [lordnull/dice.js#10]
It'd be nice to have this available on npm as well, for use with a browserify environment or even just using it with node instead of in a browser.

**Comment by lordnull** [comment]
Before I publish on npm, I'd like someone to take a look at #11 to ensure it is sane.

**Comment by seiyria** [comment]
This seems ok to me (just having a cursory glance through it), but definitely it's a good idea to get another opinion.

**Comment by lordnull** [comment]
By merging in #11, still has been resolved!

Note that there has been a minor api change, instead of needing to dice.parse.parse and dice.eval.eval, you can just do dice.parse and dice.eval directly.

**Comment by seiyria** [comment]
Great. That's exciting! I'll give it a try today or tomorrow and get back to you.

**Comment by seiyria** [comment]
Yep! It worked perfectly as a drop-in solution. Thanks so much!
