### ISSUE TITLE
true min and max

### ISSUE THREAD

**Issue by seiyria** [lordnull/dice.js#14]
Looking at how [min and max are calculated in the statistics](https://github.com/lordnull/dice.js/blob/master/src/dice.js#L28-L29), it occurred to me that it won't necessarily give the true min and max. In the simple case of 1d20, I would expect:

min: 1,
max: 20,
mean: 10

... but I could plausibly get:

min: 10,
max: 10,
mean: 10

if the stars aligned that way.

I understand this is for statistics purposes, but would it be possible to also get a true min and max (looking at your grammar, this should be easily doable with some recursion) added to the statistics objects?

**Comment by lordnull** [comment]
Take a look at #15 , see if it fits what you need.

**Comment by seiyria** [comment]
It seems great. I'll test it when I get the chance. Thanks!
