### ISSUE TITLE
What if I want to roll str/2?

### ISSUE THREAD

**Issue by seiyria** [lordnull/dice.js#16]
For example, I want to roll `1d([str]/2)`. This throws a peg exception, because it was only expecting `1d[str]` or a real number.

**Comment by lordnull** [comment]
The floor, ceil, and round flags are designed to help with just this scenario. The grammar specifies that the numbers in a roll (`x(d|w)n..m`) must be integer values. The f,c, and r flags are defined as integer values.

So you can what you want by adding a flag: `1df([str]/2)`.

These (should) also work:

```
f(3d6)d10
r[str]wf([str]/2)..c([str]/2)
```

**Comment by seiyria** [comment]
Strange, I thought I had tried 1df([str]/2). My mistake, then! Thank you! That's probably a lot less dumb than `f(1d[str] / 2) + 1`.
