### ISSUE TITLE
Extend floor, ceil, round to more than variables.

### ISSUE THREAD

**Issue by Morgul** [lordnull/dice.js#2]
It would be incredibly useful to be able to do the following:

`d20 + floor([level] / 2)`

The uses should be pretty obvious; it means that instead of having to pre-calculate half level, etc. we can instead do the calculation right in the dice string.

**Comment by lordnull** [comment]
This feature was in the branch https://github.com/lordnull/dice.js/tree/feature-mw-sub-expressions , but had never been merged in (or even reviewed). Take a look at #3 and give it a plus 1 if it meets your needs.

**Comment by lordnull** [comment]
Resolved in pull #3 .
