### ISSUE TITLE
Drop/Keep support?

### ISSUE THREAD

**Issue by ericscheid** [lordnull/dice.js#26]
Could dice.js be extended to support "keep n highest" or "drop n lowest" (and variations)?

With some defaults for concision (e.g. `4d6d1`, `2d20k`, etc)

**Comment by lordnull** [comment]
I like the idea, and could open the door to being able to add syntax for all sorts of roll modifiers if implemented right. the `4d6d1` looks like it could cause some ambiguity. If there's a seperator between the dice expression and the modifiers, I think that'll solve it.

While I've got ideas for re-rolls and explodes, I'll put that as a seperate issue.

`4d6:d` - drop lowest die
`4d6:d1` - drop lowest die
`2d20:k` - keep highest die
`4d6:k3` - keep 3 highest die

Adding in some longer forms if readibiliy is needed:

`4d6:drop`
`4d6:drop1`
`4d6:keep3`
`2d20:keep`

**Comment by lordnull** [comment]
Here's what I've settled on for the short form:
`4d6:h3` - keep the highest 3 results.
`2d20:h` - keep only the highest result.
`4d6:l1` - drop the lowest 1 result.
`2d20:l` - drop the lowest result.
`4d6:rr` - re-roll the minimum result once.

And a more verbose form which has more options and can be combined together:

`4d6{ keep highest 3 }`
`4d6{ drop lowest 1 }`
`4d6{ drop lowest }`
`2d20{ keep highest }`
`2d20{ keep lowest }`
`3d6{ reroll 1 1x }`
`3d6{ reroll <2 1x}`
`4d6{ reroll 1 3x; keep highest 3}` ( for the super generous gm's ).

**Comment by ericscheid** [comment]
> `2d20:H` - keep only the highest result
`2d20:L` - drop the lowest result

Something seems off here .. the `H` or `L` is doing double-duty of a) determining which die to action, and b) what that action is (ie. drop, or keep). 

In the terse format, how would one roll with disadvantage (i.e. `2d20{keep lowest}`) [1] 
What would be the terse format for `4d6{keep lowest 3}` though? (a truly sucky way to roll for stats)

Some defaults would be reasonable: `H` implies keep, `L` implies drop, (and `K` implies highest, `D` implies lowest), assume 1 die only, and these defaults can be explicitly overrideen like `4d6:DL1` or `2d20:KL`.


_[1] Well, technically, `2d20{drop highest}` is exactly the same as `2d20{keep lowest}` as there are only 2 dice involved._

**Comment by lordnull** [comment]
I like the `4d6:dl` and `4d6:kh3` type forms. Keeps it concise without losing too much information. I also notice you’re using capitals for the short forms, so I’ll be sure to make the short forms case-insensitive.

**Comment by ericscheid** [comment]
The CAPS were mostly to be clear that `l` was not `1` =)

**Comment by lordnull** [comment]
I’ve created a branch that implements the change. I ended up basically re-writing the underlying system because it had been so long that:

1: I didn’t remember all the data structures used, and they were not documented / self-named.
2: The peg library was no longer being updated
3: Many other dependencies were out of date.

Biggest changes:

* Using typescript to describe the grammar after it has been parsed.
* Removed the use of the karma test framework since Jasmine was able to do everything I needed.
* Removed out of date build helpers .

All this to extend the syntax a bit…still useful work I hope.

**Comment by ericscheid** [comment]
Great stuff!

I'll test it out soon (when it becomes available, lol)

**Comment by lordnull** [comment]
Resolved by #27 and published to npm.
