### ISSUE TITLE
some clarification on using dice.roll

### ISSUE THREAD

**Issue by seiyria** [lordnull/dice.js#5]
Love the library, it seems very powerful.

One thing that was really confusing for me at first was when I saw this:

![](http://i.imgur.com/HFR72JB.png)

It took me a while to realize I had to coerce roll into a primitive (`+dice.roll('1d4')`) when doing a console.log to see the actual value.

**Comment by lordnull** [comment]
Does #6 address this adequately?

**Comment by seiyria** [comment]
I think that does it, thanks!
