### ISSUE TITLE
average roll functionality

### ISSUE THREAD

**Issue by seiyria** [lordnull/dice.js#9]
Sometimes, it'd be nice to see what an average roll looks like for comparison purposes. For example, I'm making a game that heavily uses dice rolls. In some cases, I want to say that "you should equip this sword, because its attack roll is higher than your dagger" and I figured using an average-case roll would be best to facilitate that. 

Coupled with this, it might be nice to have `min` and `max` functionality as well.

**Comment by lordnull** [comment]
I've added `dice.statistics`. It provides the most basic of statistics, but does also return the result set so one can use that to get more advanced analysis going on.

``` javascript
// these lines all mean the same thing: evaluate and roll the dice string '1d6' 1000 times with an
// empty scope, and return the results as a object.
dice.statistics('1d6');
dice.statistics('1d6', {});
dice.statistics('1d6', 1000);
dice.statistics('1d6', {}, 1000);

var resultObject = dice.statistics('1d[one]', {'one': 1}, 50);
resultObj.min === 1;
resultObj.max === 1;
resultObj.mean === 1;
// hard to show as a simple equality, but you also get the actual results from the rolls.
// Those results being numbers with attached breakdowns of what needed to happen to generate
// said numbers.
// In our case, it's an array of length 50 filled with 1's.
resultObj.results;
```

**Comment by seiyria** [comment]
That sounds fantastic. Thank you so much!
